"""
Module to filter mobile phones based on user input and score them based on the requirements provided by the user.
"""

import json
import os

import pandas as pd


class FilterMobilesBasedOnUserInputs:
    """Class that takes the input generated by the AI in terms of requirement and recomends mobile Phones"""

    def __init__(self, dictionary_of_requirements):
        """Constructor of the FilterMobilesBasedOnUserInputs class"""

        # Variable to store the dictionary of requirements extracted from the user input by the AI
        self._dictionary_of_requirements = dictionary_of_requirements

        # Variable to store the ratings for each priority level
        self._ratings = {
            "high_priority": 3,
            "mid_priority": 2,
            "low_priority": 1,
        }

        # Variable to store the refined dataset after filtering and scoring the mobile phones based on user input
        self._refined_dataset = pd.read_csv(
            os.path.join(
                os.path.dirname(__file__),
                "refined_mobile_data",
                "RefinedMobileDataSet.csv",
            )
        )

        # Variable to store the directory where the ratings JSON files are stored
        self._ratings_json_directory = os.path.join(
            os.path.dirname(__file__), "ratings_files"
        )

    def filter_data_based_on_user_input(self):
        """Method to filter mobile phones based on user input"""

        # If there are hard requirements set by the user, we filter the data based on those requirements.
        if self._dictionary_of_requirements["requirements"] is not None:
            for key, value in self._dictionary_of_requirements["requirements"].items():
                if value is not None:
                    if key == "Company Name":
                        self._refined_dataset = self._refined_dataset[
                            self._refined_dataset["Company Name"] == value
                        ]
                    if key == "Model Name":
                        self._refined_dataset = self._refined_dataset[
                            self._refined_dataset["Model Name"].str.contains(value)
                        ]
                    if key == "Mobile Weight":
                        self._refined_dataset = self._refined_dataset[
                            self._refined_dataset["Mobile Weight"] <= value
                        ]
                    if key == "RAM":
                        self._refined_dataset = self._refined_dataset[
                            self._refined_dataset["RAM"] >= value
                        ]
                    if key == "Front Camera":
                        self._refined_dataset = self._refined_dataset[
                            self._refined_dataset["Front Camera"] >= value
                        ]
                    if key == "Back Camera":
                        self._refined_dataset = self._refined_dataset[
                            self._refined_dataset["Back Camera"] >= value
                        ]
                    if key == "Processor":
                        self._refined_dataset = self._refined_dataset[
                            self._refined_dataset["Processor"].str.contains(value)
                        ]
                    if key == "Battery Capacity":
                        self._refined_dataset = self._refined_dataset[
                            self._refined_dataset["Battery Capacity"] >= value
                        ]
                    if key == "Screen Size":
                        self._refined_dataset = self._refined_dataset[
                            self._refined_dataset["Screen Size"] >= value
                        ]
                    if key == "Launch Price":
                        self._refined_dataset = self._refined_dataset[
                            self._refined_dataset["Launched Price (India)"] <= value
                        ]
                    if key == "Launched Year":
                        self._refined_dataset = self._refined_dataset[
                            self._refined_dataset["Launched Year"] >= value
                        ]
                    if key == "Storage":
                        self._refined_dataset = self._refined_dataset[
                            self._refined_dataset["Storage"] >= value
                        ]

    def score_mobile_phones_based_on_user_input(self):
        """Method to score the mobile phones based on user input"""

        # Variables to store the ratings for each company, model and processor
        company_ratings = {}
        model_ratings = {}
        processor_ratings = {}

        with open(
            os.path.join(self._ratings_json_directory, "company_ratings.json")
        ) as ratings_file:
            company_ratings = json.load(ratings_file)

        with open(
            os.path.join(self._ratings_json_directory, "model_ratings.json")
        ) as ratings_file:
            model_ratings = json.load(ratings_file)

        with open(
            os.path.join(self._ratings_json_directory, "processor_ratings.json")
        ) as ratings_file:
            processor_ratings = json.load(ratings_file)

        self._refined_dataset["Company Rating"] = self._refined_dataset[
            "Company Name"
        ].map(company_ratings)
        self._refined_dataset["Model Rating"] = self._refined_dataset["Model"].map(
            model_ratings
        )
        self._refined_dataset["Processor Rating"] = self._refined_dataset[
            "Processor"
        ].map(processor_ratings)

        # Scoring the mobile phones based on the requirements provided by the user.
        # The scoring is done based on the priority of each requirement. The higher the priority, the higher the score.
        self._refined_dataset["Score"] = 0
        for key, value in self._dictionary_of_requirements["specifications"].items():
            priority_weight = self._ratings.get(value, 1)

            if key == "Company Name":
                self._refined_dataset["Score"] = (
                    self._refined_dataset["Score"]
                    + self._refined_dataset["Company Rating"] * priority_weight
                )
            if key == "Model Name":
                self._refined_dataset["Score"] = (
                    self._refined_dataset["Score"]
                    + self._refined_dataset["Model Rating"] * priority_weight
                )
            if key == "Mobile Weight":
                self._refined_dataset["Score"] = (
                    self._refined_dataset["Score"]
                    - (self._refined_dataset["Mobile Weight"] / 100.0) * priority_weight
                )
            if key == "RAM":
                self._refined_dataset["Score"] = (
                    self._refined_dataset["Score"]
                    + (self._refined_dataset["RAM"] / 10.0) * priority_weight
                )
            if key == "Front Camera":
                self._refined_dataset["Score"] = (
                    self._refined_dataset["Score"]
                    + (self._refined_dataset["Front Camera"] / 10.0) * priority_weight
                )
            if key == "Back Camera":
                self._refined_dataset["Score"] = (
                    self._refined_dataset["Score"]
                    + (self._refined_dataset["Back Camera"] / 10.0) * priority_weight
                )
            if key == "Processor":
                self._refined_dataset["Score"] = (
                    self._refined_dataset["Score"]
                    + self._refined_dataset["Processor Rating"] * priority_weight
                )
            if key == "Battery Capacity":
                self._refined_dataset["Score"] = (
                    self._refined_dataset["Score"]
                    + (self._refined_dataset["Battery Capacity"] / 1000.0)
                    * priority_weight
                )
            if key == "Screen Size":
                self._refined_dataset["Score"] = (
                    self._refined_dataset["Score"]
                    + (self._refined_dataset["Screen Size"] / 10.0) * priority_weight
                )
            if key == "Launch Price":
                self._refined_dataset["Score"] = (
                    self._refined_dataset["Score"]
                    - (self._refined_dataset["Launched Price (India)"] / 10000.0)
                    * priority_weight
                )
            if key == "Launched Year":
                self._refined_dataset["Score"] = (
                    self._refined_dataset["Score"]
                    + (self._refined_dataset["Launched Year"] / 10.0) * priority_weight
                )
            if key == "Storage":
                self._refined_dataset["Score"] = (
                    self._refined_dataset["Score"]
                    + (self._refined_dataset["Storage"] / 100.0) * priority_weight
                )

        self._refined_dataset = self._refined_dataset.sort_values(
            by=["Score"], ascending=False
        )
        return self._refined_dataset
