import os
import pandas as pd

class FilterMobilesBasedOnUserInputs():

    """Class that takes the input generated by the AI in terms of requirement and recomends mobile Phones"""

    def __init__(self, dictionary_of_requirements):
        """Constructor of the FilterMobilesBasedOnUserInputs class"""
        self._dictionary_of_requirements = dictionary_of_requirements
        self._ratings = {
            "high_priority": 3,
            "mid_priority": 2,
            "low_priority": 1,
        }
        self._refined_dataset = pd.read_csv(os.path.join(os.path.dirname(os.path.dirname(__file__)), "refined_mobile_data", "RefinedMobileDataSet.csv"))

    def recommender(self):
        """Method to recommend mobile phones"""
        if self._dictionary_of_requirements["requirements"] is not None:
            for key, value in self._dictionary_of_requirements["requirements"].items():
                if value is not None:
                    if key == "Company Name":
                        self._refined_dataset = self._refined_dataset[self._refined_dataset["Company Name"]==value]
                    if key == "Model Name":
                        self._refined_dataset = self._refined_dataset[self._refined_dataset["Model Name"].str.contains(value)]
                    if key == "Mobile Weight":
                        self._refined_dataset = self._refined_dataset[self._refined_dataset["Mobile Weight"] <= value]
                    if key == "RAM":
                        self._refined_dataset = self._refined_dataset[self._refined_dataset["RAM"] >= value]
                    if key == "Front Camera":
                        self._refined_dataset = self._refined_dataset[self._refined_dataset["Front Camera"] >= value]
                    if key == "Back Camera":
                        self._refined_dataset = self._refined_dataset[self._refined_dataset["Back Camera"] >= value]
                    if key == "Processor":
                        self._refined_dataset = self._refined_dataset[self._refined_dataset["Processor"].str.contains(value)]
                    if key == "Battery Capacity":
                        self._refined_dataset = self._refined_dataset[self._refined_dataset["Battery Capacity"] >= value]
                    if key == "Screen Size":
                        self._refined_dataset = self._refined_dataset[self._refined_dataset["Screen Size"] >= value]
                    if key == "Launch Price":
                        self._refined_dataset = self._refined_dataset[self._refined_dataset["Launched Price (India)"] <= value]
                    if key == "Launched Year":
                        self._refined_dataset = self._refined_dataset[self._refined_dataset["" \
                        "Launched Year"] >= value]
                    if key == "Storage":
                        self._refined_dataset = self._refined_dataset[self._refined_dataset["Storage"] >= value]
            
        print(self._refined_dataset)
